### ISSUE TITLE
Date and Boolean data type

### ISSUE THREAD

**Issue by thomplth** [thomplth/ridesharing-system-db#1]
`"taken char(1) not null," + // Y/N statment`

`"start_time char(19) not null," + // java.time in “YYYY-MM-DD HH:mm:ss” format`
`"end_time char(19) not null," + // java.time in “YYYY-MM-DD HH:mm:ss” format`

I am assuming:
`taken` to be a char of 'Y' or 'N', indicating whether the request is taken or not;
`start_time` and `end_time` to be strings created by java.time ([reference](https://stackoverflow.com/questions/61517912/convert-input-date-in-yyyy-mm-ddthhmmssssshhmm-format-to-the-java-sql-time))

Let me know if you want to alter the way of implementing.

**Comment by ivanwong201127** [comment]
Wonder if we can use the DATETIME datatype for start_time and end_time, then we can compare directly without having to parse them.

**Comment by thomplth** [comment]
Updated. We are now using DATETIME datatype for start_time and end_time, and the corresponding Java datatype should be java.sql.Timestamp. ([reference](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types?view=sql-server-ver15))
